#!/usr/bin/env python3
"""Scaffold (and optionally run) an isolated Godot project for validating one
.unitypackage against this checkout of Unidot.

Each package gets its own project, so its asset database, import cache and
output tree cannot be contaminated by a previous package. That isolation is what
makes the per-package figures in docs/packages/ attributable.

    tools/validate_package.py "~/art/POLYGON - Prototype Pack.unitypackage" --run

By default the project is created next to the package under a directory named
after it. The Unidot revision used is recorded in the project directory so a
report can state what it was produced with.

Re-running with --clean wipes the previous import (the output tree, the asset
database and Godot's own .godot cache) but keeps the project, which is the
correct reset: deleting only the output tree leaves stale artifacts in .godot
that will skew the next run.
"""
import argparse
import json
import os
import re
import shutil
import subprocess
import sys

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_GODOT = "/Applications/Godot_mono.app/Contents/MacOS/Godot"
OUTPUT_ROOT = "res://Unidot"

PROJECT_GODOT = """config_version=5

[application]

config/name="{name}"
config/features=PackedStringArray("{features}")

[editor_plugins]

enabled=PackedStringArray("res://addons/auto_import_bootstrap/plugin.cfg", "res://addons/unidot_importer/plugin.cfg")
"""

PLUGIN_CFG = """[plugin]

name="auto_import_bootstrap"
description="Drive a unidot package import headlessly"
author="unidot validation"
version="1.0"
script="bootstrap.gd"
"""

BOOTSTRAP_GD = '''@tool
extends EditorPlugin

# Generated by tools/validate_package.py. Drives package_import_dialog without a
# user, so a package can be imported by running the editor headless:
#   Godot --headless --editor .

const PKG := {pkg!r}
const OUTPUT_ROOT := {output_root!r}
const SETTLE_SECONDS := 15.0

var package_import_dialog = null
var poll_timer: Timer = null
var started := false
var quitting := false


func _enter_tree() -> void:
	call_deferred("_start")


func _start() -> void:
	if started:
		return
	started = true
	print("AUTO_IMPORT_BOOTSTRAP: starting import of ", PKG)
	var pid = load("res://addons/unidot_importer/package_import_dialog.gd").new()
	package_import_dialog = pid
	pid.auto_import = true
	pid.editor_plugin = self
	pid.file_dialog = null
	pid.import_output_root_override = OUTPUT_ROOT
	pid.import_output_root_override_set = true
	pid._show_importer_common()
	pid._selected_package(PKG)
	poll_timer = Timer.new()
	poll_timer.wait_time = 5.0
	poll_timer.autostart = true
	get_editor_interface().get_base_control().add_child(poll_timer)
	poll_timer.timeout.connect(_poll)


func _poll() -> void:
	if quitting:
		return
	var pid = package_import_dialog
	if pid != null and pid.get("import_finished"):
		quitting = true
		print("AUTO_IMPORT_BOOTSTRAP: import finished; letting the editor settle")
		poll_timer.stop()
		await get_tree().create_timer(SETTLE_SECONDS).timeout
		get_tree().quit()
'''


def slugify(name: str) -> str:
	slug = re.sub(r"[^A-Za-z0-9]+", "_", name).strip("_")
	return slug or "package"


def godot_feature_version(godot: str) -> str:
	# project.godot must declare the engine series it was made for, or Godot
	# treats the project as needing conversion on open.
	try:
		out = subprocess.run([godot, "--version"], capture_output=True, text=True, check=True)
		m = re.match(r"(\d+\.\d+)", out.stdout.strip())
		if m:
			return m.group(1)
	except (subprocess.CalledProcessError, FileNotFoundError, OSError):
		pass
	return "4.4"


def unidot_revision() -> str:
	try:
		out = subprocess.run(
			["git", "-C", REPO_ROOT, "rev-parse", "--short", "HEAD"],
			capture_output=True, text=True, check=True,
		)
		rev = out.stdout.strip()
		dirty = subprocess.run(
			["git", "-C", REPO_ROOT, "status", "--porcelain", "--untracked-files=no"],
			capture_output=True, text=True, check=True,
		).stdout.strip()
		return rev + ("-dirty" if dirty else "")
	except (subprocess.CalledProcessError, FileNotFoundError):
		return "unknown"


def sync_addon(project_dir: str) -> None:
	dest = os.path.join(project_dir, "addons", "unidot_importer")
	os.makedirs(os.path.dirname(dest), exist_ok=True)
	# rsync keeps every validation project on the same revision as this checkout.
	subprocess.run(
		["rsync", "-a", "--delete", "--exclude", ".git", REPO_ROOT + "/", dest + "/"],
		check=True,
	)


def write_bootstrap(project_dir: str, package_path: str) -> None:
	plugin_dir = os.path.join(project_dir, "addons", "auto_import_bootstrap")
	os.makedirs(plugin_dir, exist_ok=True)
	with open(os.path.join(plugin_dir, "plugin.cfg"), "w") as f:
		f.write(PLUGIN_CFG)
	with open(os.path.join(plugin_dir, "bootstrap.gd"), "w") as f:
		f.write(BOOTSTRAP_GD.format(pkg=package_path, output_root=OUTPUT_ROOT))


def clean_import(project_dir: str) -> None:
	# All three: leaving .godot behind keeps stale imported artifacts around.
	for rel in ("Unidot", ".godot", "unidot_asset_database.res"):
		target = os.path.join(project_dir, rel)
		if os.path.isdir(target):
			shutil.rmtree(target)
		elif os.path.exists(target):
			os.remove(target)


def main() -> int:
	parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
	parser.add_argument("package", help="path to the .unitypackage to validate")
	parser.add_argument("--name", help="project directory name (default: derived from the package filename)")
	parser.add_argument("--root", help="where to create the project (default: alongside the package)")
	parser.add_argument("--godot", default=os.environ.get("GODOT", DEFAULT_GODOT), help="Godot binary (default: $GODOT or the macOS app path)")
	parser.add_argument("--clean", action="store_true", help="wipe a previous import before running")
	parser.add_argument("--run", action="store_true", help="run the headless import after scaffolding")
	args = parser.parse_args()

	package_path = os.path.abspath(os.path.expanduser(args.package))
	if not os.path.isfile(package_path):
		print("No such package: " + package_path, file=sys.stderr)
		return 1

	name = args.name or slugify(os.path.basename(package_path).rsplit(".unitypackage", 1)[0])
	root = os.path.abspath(os.path.expanduser(args.root)) if args.root else os.path.dirname(package_path)
	project_dir = os.path.join(root, name + "_validate")

	os.makedirs(project_dir, exist_ok=True)
	features = godot_feature_version(args.godot)
	with open(os.path.join(project_dir, "project.godot"), "w") as f:
		f.write(PROJECT_GODOT.format(name=name, features=features))
	sync_addon(project_dir)
	write_bootstrap(project_dir, package_path)

	revision = unidot_revision()
	with open(os.path.join(project_dir, "validation_context.json"), "w") as f:
		json.dump({"package": package_path, "unidot_revision": revision, "output_root": OUTPUT_ROOT}, f, indent=2)
		f.write("\n")

	print("project:  " + project_dir)
	print("package:  " + package_path)
	print("unidot:   " + revision)
	if revision.endswith("-dirty"):
		print("warning:  the checkout has uncommitted changes; this run is not reproducible")

	if args.clean:
		clean_import(project_dir)
		print("cleaned:  Unidot/, .godot/, unidot_asset_database.res")

	if not args.run:
		print("\nTo import:")
		print('  cd "%s" && "%s" --headless --editor . > import.log 2>&1' % (project_dir, args.godot))
		return 0

	if not os.path.exists(args.godot):
		print("No Godot binary at " + args.godot + " (set --godot or $GODOT)", file=sys.stderr)
		return 1

	log_path = os.path.join(project_dir, "import.log")
	print("\nimporting, this takes a while; log -> " + log_path)
	with open(log_path, "w") as log:
		result = subprocess.run(
			[args.godot, "--headless", "--editor", "."],
			cwd=project_dir, stdout=log, stderr=subprocess.STDOUT,
		)
	if result.returncode != 0:
		print("Godot exited with " + str(result.returncode) + "; see " + log_path, file=sys.stderr)
		return result.returncode

	with open(log_path, errors="ignore") as log:
		text = log.read()
	if "AUTO_IMPORT_BOOTSTRAP: import finished" not in text:
		print("Import did not report completion; see " + log_path, file=sys.stderr)
		return 1
	print("import finished")
	print("  engine ERROR lines:    " + str(text.count("\nERROR:")))
	print("  case-mismatch warnings:" + str(text.count("Case mismatch")))
	print("\nOutput tree: " + os.path.join(project_dir, "Unidot"))
	return 0


if __name__ == "__main__":
	sys.exit(main())
